# Generated by Django 2.0.7 on 2018-09-09 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Radio', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='photo',
            field=models.ImageField(blank=True, default='album_art/profile_pics/avatar.png', upload_to='album_art/profile_pics'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='recently_played',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Radio.Song'),
        ),
    ]
